import { describe, expect, it, vi } from 'vitest';

import { performWalkthrough } from './perform';

import type { Actor, Present } from './actor';
import type { Step } from './script';

/** What the stub actor was asked to do, in order. */
type Done = string;

const stubActor = ({
  presentTargets,
  text = 'word',
}: {
  /** Which testIDs `appears` should say turned up. */
  presentTargets?: string[];
  text?: string;
} = {}) => {
  const done: Done[] = [];
  const waitedMs: number[] = [];
  const proven = (testId: string) => ({ testId }) as unknown as Present;

  const actor = {
    awaitReady: vi.fn(async (testId: string) => {
      done.push(`ready ${testId}`);
      return proven(testId);
    }),
    click: vi.fn(async ({ testId }: Present) => {
      done.push(`click ${testId}`);
    }),
    type: vi.fn(async ({ testId }: Present, value: string) => {
      done.push(`type ${testId}=${value}`);
    }),
    fill: vi.fn(async ({ testId }: Present, value: string) => {
      done.push(`fill ${testId}=${value}`);
    }),
    awaitScreen: vi.fn(async (testId: string) => {
      done.push(`screen ${testId}`);
    }),
    revealBottom: vi.fn(async ({ testId }: Present) => {
      done.push(`scroll ${testId}`);
    }),
    linger: vi.fn(async (ms: number) => {
      done.push(`hold ${ms}`);
    }),
    textOf: vi.fn(async (testId: string) => `${text}-${testId.slice(-1)}`),
    setClipboard: vi.fn(async (value: string) => {
      done.push(`clipboard ${value}`);
    }),
    appears: vi.fn(
      async (
        testId: string,
        { required, timeout }: { required: boolean; timeout?: number },
      ) => {
        // Recorded, because how long an optional step is given is a decision the
        // app makes and nothing could observe it before.
        waitedMs.push(timeout ?? 0);
        const there = presentTargets?.includes(testId) ?? false;
        if (!there && required) throw new Error(`${testId} never appeared`);
        return there;
      },
    ),
    count: vi.fn(async () => 0),
    interactions: () => [],
  } as unknown as Actor;

  return { actor, done, waitedMs };
};

describe('performWalkthrough', () => {
  it('proves a control is present before every interaction', async () => {
    // The reactivity guarantee at runtime: an interaction is always preceded by
    // the wait that mints its proof, never the other way round.
    const { actor, done } = stubActor();

    await performWalkthrough(actor, [{ do: 'click', target: 'a-button' }], {});

    expect(done).toEqual(['ready a-button', 'click a-button']);
  });

  it('refuses to use a value it was never given', async () => {
    // Loud, because the alternative is typing the word "undefined" into a
    // password field and finding out four screens later.
    const { actor } = stubActor();

    await expect(
      performWalkthrough(
        actor,
        [{ do: 'type', target: 'a-field', value: 'password' }],
        {},
      ),
    ).rejects.toThrow(/password before it was known/);
  });

  it('binds what it reads off the page for later steps', async () => {
    // The destination phrase is generated by the app mid-run and is the only
    // only copy of what the run produced.
    const { actor, done } = stubActor({ text: 'w' });

    const learned = await performWalkthrough(
      actor,
      [
        {
          do: 'capture',
          as: 'recoveredCode',
          wordTemplate: 'word-{index}',
          count: 3,
        },
        {
          do: 'paste',
          target: 'phrase',
          value: 'recoveredCode',
        },
      ],
      {},
    );

    expect(learned.recoveredCode).toBe('w-1 w-2 w-3');
    expect(done).toContain('fill phrase=w-1 w-2 w-3');
  });

  it('skips an optional branch when its control never appears', async () => {
    // The wizard's password prompt is usually absent, because the app lock is
    // already unlocked. Failing there would fail honest takes.
    const { actor, done } = stubActor({ presentTargets: [] });

    await performWalkthrough(
      actor,
      [
        {
          do: 'ifPresent',
          target: 'a-prompt',
          required: false,
          then: [{ do: 'click', target: 'confirm' }],
        },
      ],
      {},
    );

    expect(done).toEqual([]);
  });

  it('runs an optional branch when its control does appear', async () => {
    const { actor, done } = stubActor({ presentTargets: ['a-prompt'] });

    await performWalkthrough(
      actor,
      [
        {
          do: 'ifPresent',
          target: 'a-prompt',
          required: false,
          then: [{ do: 'click', target: 'confirm' }],
        },
      ],
      {},
    );

    expect(done).toEqual(['ready confirm', 'click confirm']);
  });

  it('fails when a required control never appears', async () => {
    // Importing the source has prompted in every observed run, and a missing
    // prompt there means the action is never confirmed, so silence is not an
    // option.
    const { actor } = stubActor({ presentTargets: [] });

    await expect(
      performWalkthrough(
        actor,
        [
          {
            do: 'ifPresent',
            target: 'a-prompt',
            required: true,
            then: [{ do: 'click', target: 'confirm' }],
          },
        ],
        {},
      ),
    ).rejects.toThrow(/never appeared/);
  });

  it('keeps what a branch learned rather than discarding it', async () => {
    // A sub-sequence used to run against a copy, so anything it captured was
    // learned and thrown away, surfacing much later as a value referred to
    // before it was known.
    const { actor } = stubActor({ presentTargets: ['a-prompt'], text: 'x' });

    const learned = await performWalkthrough(
      actor,
      [
        {
          do: 'ifPresent',
          target: 'a-prompt',
          required: false,
          then: [
            {
              do: 'capture',
              as: 'recoveredCode',
              wordTemplate: 'w-{index}',
              count: 1,
            },
          ],
        },
      ],
      {},
    );

    expect(learned.recoveredCode).toBe('x-1');
  });

  it('performs a whole script in the order it is written', async () => {
    const script: Step<string>[] = [
      { do: 'click', target: 'start' },
      { do: 'awaitScreen', target: 'a-screen' },
      { do: 'setClipboard', value: 'sourcePhrase' },
      { do: 'hold', ms: 500, note: 'reading' },
      { do: 'scrollTo', target: 'submit' },
      { do: 'click', target: 'submit' },
    ];
    const { actor, done } = stubActor();

    await performWalkthrough(actor, script, { sourcePhrase: 'a phrase' });

    expect(done).toEqual([
      'ready start',
      'click start',
      'screen a-screen',
      'clipboard a phrase',
      'hold 500',
      'ready submit',
      'scroll submit',
      'ready submit',
      'click submit',
    ]);
  });
});

describe('an app can say how long its optional step gets', () => {
  it("waits the app's own timeout rather than the library default", async () => {
    // The defaults are one app's stopwatch readings: a prompt that mounts with
    // its screen was already there 1.4s after the click. An app whose optional
    // interstitial needs a round trip would be called absent and skipped, and
    // the next step would then click something hidden behind it.
    const { actor, waitedMs } = stubActor();

    await performWalkthrough(
      actor,
      [
        {
          do: 'ifPresent',
          target: 'a-slow-prompt',
          required: false,
          timeoutMs: 9000,
          then: [],
        },
      ],
      {},
    );

    expect(waitedMs).toEqual([9000]);
  });

  it('falls back to the library default when the app says nothing', async () => {
    const { actor, waitedMs } = stubActor();

    await performWalkthrough(
      actor,
      [{ do: 'ifPresent', target: 'a-prompt', required: false, then: [] }],
      {},
    );

    expect(waitedMs).toEqual([2500]);
  });
});
